#!/usr/bin/env bash
# nginx
apt-get -y upgrade
apt-get -y update
apt-get -y install nginx
echo "Ceci n'est pas une page" > /var/www/html/index.nginx-debian.html
new="error_page 404 \/404_error.html;\\n\\tlocation = \/404_error.html {\\n\\t\\troot \/var\/www\/html;\\n\\t\\tinternal;\\n\\t}"
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-available/default
service nginx start
