#!/usr/bin/env bash
# nginx
apt-get -y upgrade
apt-get -y update
apt-get -y install haproxy
echo "ENABLED=1" >> /ect/default/haproxy
echo "listen http-incoming
       mode http
       bind *:80
       balance roundrobin
       server 1296-web-01 35.229.28.179:80 check
       server 1296-web-02 54.234.166.97:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy start
