#!/usr/bin/env bash
#
echo ps -p $$ > /var/run/holbertonscript.pid
trap "echo Y U no love me?!" SIGINT
trap 'echo I hate the kill command; rm -rf /var/run/holbertonscript.pid; exit' SIGTERM
trap "rm -rf /var/run/holbertonscript.pid; exit" SIGQUIT
while((1));
do
    echo "To infinity and beyond"
    sleep 2
done
